;(function($){'use strict';var tombuildTheme={init:function(){this.config();this.events();},config:function(){this.config={$window:$(window),$document:$(document),};},events:function(){var self=this;$(document).ready(function(){self.customCursor();});self.preLoader();self.searchIcon();self.cartIcon();self.headerFixed();self.scrollToTop();self.hamburgerMenu();self.quantityButton();self.responsiveVideos();self.footerFixed();self.formReveal();self.progressBar();self.megaMenu();},preLoader:function(){if($().animsition){if($('.animsition.image').length){var $url=$('.animsition.image').data('preloader');var $cls=$('.animsition.image').data('preclass');$('.animsition').animsition({inClass:'fade-in',outClass:'fade-out',inDuration:500,outDuration:500,loading:true,loadingParentElement:'body',loadingClass:'animsition-image',loadingInner:'<img src="'+$url+'"'+'class="'+$cls+'" alt="Image" />',timeout:true,timeoutCountdown:5000,onLoadEvent:true,browser:['-webkit-animation-duration','-moz-animation-duration','animation-duration'],overlay:false,overlayClass:'animsition-overlay-slide',overlayParentElement:'body',transition:function(url){window.location.href=url;}});}else{$('.animsition').animsition({inClass:'fade-in',outClass:'fade-out',inDuration:500,outDuration:500,loading:true,loadingParentElement:'body',loadingClass:'animsition-loading',timeout:true,timeoutCountdown:5000,onLoadEvent:true,browser:['-webkit-animation-duration','-moz-animation-duration','animation-duration'],overlay:false,overlayClass:'animsition-overlay-slide',overlayParentElement:'body',transition:function(url){window.location.href=url;}});}}},responsiveVideos:function(){if($().fitVids){$('.tombuild-container').fitVids();}},searchIcon:function(){if($('.search-trigger').length){var search_wrap=$('.search-style-fullscreen');var search_trigger=$('.search-trigger');var search_field=search_wrap.find('.search-field');search_trigger.on('click',function(e){if(!search_wrap.hasClass('search-opened')){search_wrap.addClass('search-opened');search_field.get(0).focus();}else if(search_field.val()===''){if(search_wrap.hasClass('search-opened'))
search_wrap.removeClass('search-opened');else search_field.get(0).focus();}else{search_wrap.find('form').get(0).submit();}
$('html').addClass('disable-scroll');e.preventDefault();return false;});search_wrap.find('.search-close').on('click',function(e){search_wrap.removeClass('search-opened');$('html').removeClass('disable-scroll');e.preventDefault();return false;});}},cartIcon:function(){$(document).on('woocommerce-cart-changed',function(e,data){if(parseInt(data.items_count,10)>=0){$('.shopping-cart-items-count').text(data.items_count)}});},headerFixed:function(){var nav=$('.tombuild-header-fixed');var sp=0;if(nav.length){var showHeader=function(){var np=$('body')[0].getBoundingClientRect().top;var st=$(window).scrollTop();if(np>sp){if(st>500){nav.addClass('fixed-show');}
if(st<300){nav.removeClass('fixed-show');}}else{nav.removeClass('fixed-show');}
sp=np}
$(window).on('scroll',showHeader);}},footerFixed:function(){if($('body').is('.footer-fixed')&&window.matchMedia('(min-width: 1025px)').matches){var content=$('#main-content'),footer=$('.tombuild-footer'),height=footer.height();content.css('margin-bottom',height+'px');}},scrollToTop:function(){$(window).scroll(function(){if($(this).scrollTop()>800){$('#scroll-top').addClass('show');}else{$('#scroll-top').removeClass('show');}});$('#scroll-top').on('click',function(){var rocket=$(this);$('html, body').animate({scrollTop:0},700,'easeInCubic');});},hamburgerMenu:function(){$('.tombuild-menu-panel').each(function(){var
t=$(this),btn=t.siblings('.tombuild-hamburger-icon'),c=t.find('.close-menu'),o=t.find('.menu-panel-overlay'),w=t.find('.menu-panel-wrap');t.find('.menu-item-has-children').children('ul').before('<span class="arrow"></span>');t.find('.menu-item-has-children > .arrow').on('click',function(){$(this).parent().toggleClass("active").siblings().removeClass("active");$(this).next("ul").slideToggle();$(this).parent().siblings().find("ul").slideUp();})
o.on('click',function(){btn.removeClass('hide');o.removeClass('show');w.animate({right:"-100%"},300,'easeInOutExpo')
$('html').removeClass('disable-scroll');});c.on('click',function(){btn.removeClass('hide');o.removeClass('show');w.animate({right:"-100%"},300,'easeInOutExpo')
$('html').removeClass('disable-scroll');});btn.on('click',function(){btn.addClass('hide');o.addClass('show');$('html').addClass('disable-scroll');w.animate({right:"0"},300,'easeInOutExpo');})})},customCursor:function(){if($('.tombuild-cursor').length){$('.tombuild-cursor').masterCursor();}},quantityButton:function(){if($('.woocommerce-page .quantity').length&&!($('.shopengine-template').length)){if(!String.prototype.getDecimals){String.prototype.getDecimals=function(){var num=this,match=(''+num).match(/(?:\.(\d+))?(?:[eE]([+-]?\d+))?$/);if(!match){return 0;}
return Math.max(0,(match[1]?match[1].length:0)-(match[2]?+match[2]:0));}}
$(document.body).on('click','.plus, .minus',function(){var $qty=$(this).closest('.quantity').find('.qty'),currentVal=parseFloat($qty.val()),max=parseFloat($qty.attr('max')),min=parseFloat($qty.attr('min')),step=$qty.attr('step');if(!currentVal||currentVal===''||currentVal==='NaN')currentVal=0;if(max===''||max==='NaN')max='';if(min===''||min==='NaN')min=0;if(step==='any'||step===''||step===undefined||parseFloat(step)==='NaN')step=1;if($(this).is('.plus')){if(max&&(currentVal>=max)){$qty.val(max);}else{$qty.val((currentVal+parseFloat(step)).toFixed(step.getDecimals()));}}else{if(min&&(currentVal<=min)){$qty.val(min);}else if(currentVal>0){$qty.val((currentVal-parseFloat(step)).toFixed(step.getDecimals()));}}
$qty.trigger('change');});}},formReveal:function(){if($('.page-give-forms').length){$('.give-btn-reveal').on('click',function(){$(this).hide();$('#give-payment-mode-select, #give_purchase_form_wrap').show();})}},progressBar:function(){if($('.give-progress-bar').length){$('.give-progress-bar').each(function(idx,el){var bar=$(el).find('>span');bar.css('width','0%');new IntersectionObserver(function e(i,n){i.forEach(function(e){if(e.isIntersecting){let w=$(el).attr('aria-valuenow');bar.css('width',w+'%');n.unobserve(e.target)}});}).observe(el);})}},megaMenu:function(){$('.tombuild-menu .megamenu').each(function(idx,el){var navPos=function(){let offset=$(el).closest('.elementor-container, .tombuild-container').offset().left-$(el).offset().left;$(el).find('> .sub-menu').css('left',offset+'px');}
navPos();$(window).on('resize',function(){navPos();})})},};tombuildTheme.init();})(jQuery);